version: '3'

services:

  mongo:
    image: mongo:3.2
    ports:
      - '27017:27017'
    logging:
      driver: none

  router:
    image: actionml/harness:ci
    ports:
      - '9090:9090'
    environment:
      MONGO_HOST: "mongo"
      REST_SERVER_HOST: "0.0.0.0"
      REST_SERVER_PORT: "9090"
    depends_on:
      - mongo
    volumes:
      - ./it/shared/logs:/app/logs
      - ./it/shared/data:/data

  elasticsearch:
    image: elasticsearch:5.6.14-alpine
    ports:
      - '9200:9200'
      - '9300:9300'

